module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  mode: 'jit',
  theme: {
    extend: {
      colors: {
        primary: '#00040f',
        secondary: '#00f6ff',
        dimWhite: 'rgba(255, 255, 255, 0.7)',
        dimBlue: 'rgba(9, 151, 124, 0.1)',
        secondary: '#323232',
        hoverColor: '#34d399',
        naiveBlue: '#027fff',
        coral: '#ff7f50',
        coralOrange: '#ffa387',
        paleBlue: '#add8e6',
        green: '#008000',
        yellowDif: '#fde68a',
        nightBlue: '#051622',
        gold: '#deb992',
        'pallid-green': '#8c9c8c',
        'white-beige': '#f4eec9',
        'dark-pallid-green': '#3a4e4f',
        'blue-tesla': '#dee5f0',
        'hover-gray': '#a9b8c9',
        'light-beige': '#f2eade',
        bordon: '#72383d',
        'dark-brown': '#322d29',
        port1: '#AC9C8D',
        port2: '#D1C7BD',
        port3: '#D9D9D9',
        port4: '#EFE9E1',
        bordon_1: '#76555C',
        'jazz_berry-jam': '#9E0050',
        swiss_coffee: '#DCD2C8',
        black_pearl: '#192331',
        paprika: '#7B2333',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        DancingScript: ['Dancing-Script', 'sans-serif'],
        Montserrat: ['Montserrat', 'sans-serif'],
        Cormorant: ['Cormorant', 'sans-serif'],
        Margarine: ['Margarine', 'sans-serif'],
      },
    },
    screens: {
      xs: '480px',
      ss: '620px',
      sm: '768px',
      md: '1060px',
      lg: '1200px',
      xl: '1700px',
    },
  },
  variants: {},
  plugins: [],
};
